#!/bin/bash
g++ temperatureClientTest.cpp network/SocketClient.cpp -o temperatureClientTest.o -pthread
g++ temperatureServer.cpp network/SocketServer.cpp network/ConnectionHandler.cpp -o temperatureServer.o -pthread
